INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'The Legend of Zelda: Breath of the Wild', 'Nintendo Switch', 15.99, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Red Dead Redemption 2', 'PlayStation 4', 12.50, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Cyberpunk 2077', 'PC', 10.00, false);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Super Mario Odyssey', 'Nintendo Switch', 14.99, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'God of War', 'PlayStation 4', 11.75, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Halo Infinite', 'Xbox Series X', 13.25, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Animal Crossing: New Horizons', 'Nintendo Switch', 16.50, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'The Witcher 3: Wild Hunt', 'PC', 9.99, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'FIFA 22', 'PlayStation 5', 18.00, false);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Call of Duty: Modern Warfare', 'Xbox One', 12.00, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Minecraft', 'PC', 7.99, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Assassin''s Creed Valhalla', 'PlayStation 5', 14.50, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Pokémon Sword', 'Nintendo Switch', 17.00, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Final Fantasy VII Remake', 'PlayStation 4', 13.99, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Forza Horizon 5', 'Xbox Series X', 15.00, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'The Last of Us Part II', 'PlayStation 4', 11.25, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Doom Eternal', 'PC', 10.50, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Splatoon 2', 'Nintendo Switch', 12.75, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Ghost of Tsushima', 'PlayStation 4', 14.00, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Gears 5', 'Xbox One', 9.75, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Resident Evil Village', 'PlayStation 5', 16.00, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'The Elder Scrolls V: Skyrim', 'PC', 8.99, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Mario Kart 8 Deluxe', 'Nintendo Switch', 15.50, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Demon''s Souls', 'PlayStation 5', 17.50, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Star Wars Jedi: Fallen Order', 'Xbox One', 12.25, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Overwatch', 'PC', 9.50, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Luigi''s Mansion 3', 'Nintendo Switch', 14.25, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Death Stranding', 'PlayStation 4', 11.00, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Halo: The Master Chief Collection', 'Xbox Series X', 13.75, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'The Sims 4', 'PC', 8.50, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Fire Emblem: Three Houses', 'Nintendo Switch', 16.75, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Horizon Zero Dawn', 'PlayStation 4', 10.25, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Sea of Thieves', 'Xbox One', 12.50, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Apex Legends', 'PC', 0.00, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Super Smash Bros. Ultimate', 'Nintendo Switch', 18.50, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Spider-Man: Miles Morales', 'PlayStation 5', 15.75, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Control', 'Xbox Series X', 11.50, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Among Us', 'PC', 0.00, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Xenoblade Chronicles 2', 'Nintendo Switch', 17.25, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Persona 5 Royal', 'PlayStation 4', 14.75, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Forza Motorsport 7', 'Xbox One', 10.00, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Valorant', 'PC', 0.00, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'The Legend of Zelda: Link''s Awakening', 'Nintendo Switch', 13.50, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Ratchet & Clank: Rift Apart', 'PlayStation 5', 16.25, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Grounded', 'Xbox Series X', 9.25, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'League of Legends', 'PC', 0.00, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Monster Hunter Rise', 'Nintendo Switch', 15.25, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Returnal', 'PlayStation 5', 17.00, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'Microsoft Flight Simulator', 'Xbox Series X', 14.00, true);
INSERT INTO GAME (id, title, platform, price_rent, disponible) VALUES (RANDOM_UUID(), 'World of Warcraft', 'PC', 12.99, true);